name: notes_example
description: A notes application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Import the provider package.
  provider: ^4.3.2+2
  path_provider: ^1.6.21
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  hive_generator: ^0.8.1
  rename: ^1.2.0


flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
